
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.25.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[override]]
  name = "github.com/go-openapi/spec"
  revision = "5bae59e25b21498baea7f9d46e9c147ec106a42e"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.4"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  #revision = "1a3f18b6b1006076ad29386083c576ca4ac59686"
  branch = "v0.0.7"
  # version = "=v0.0.5"
