module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/mattn/go-isatty v0.0.12 // indirect
	github.com/spf13/cobra v1.1.1 // indirect
	sigs.k8s.io/controller-tools v0.3.0 // cmd/controller-gen
)
