module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/google/go-cmp v0.5.2 // indirect
	golang.org/x/tools v0.0.0-20201027180023-8dabb740183d // indirect
	mvdan.cc/gofumpt v0.0.0-20201027171050-85d5401eb0f6 // gofumports
)
