module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.17

require github.com/openshift/release v0.0.0-20201103082000-d8009dcf7503 // tools/junitreport

require github.com/openshift/origin v4.1.0+incompatible // indirect
