module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.17

replace k8s.io/klog => github.com/simonpasquier/klog-gokit v0.1.0

require github.com/prometheus/prometheus v1.8.2-0.20200522113006-f4dd45609a05 // cmd/promtool
