apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-metrics-monitor
spec:
  endpoints:
  - authorization:
      credentials:
        key: token
        name: elasticsearch-operator-metrics-token
      type: bearer
    interval: 30s
    path: /metrics
    scheme: https
    scrapeTimeout: 10s
    targetPort: 8443
    tlsConfig:
      ca:
        secret:
          key: service-ca.crt
          name: elasticsearch-operator-metrics-token
      serverName: elasticsearch-operator-metrics.openshift-operators-redhat.svc
  selector:
    matchLabels:
      name: elasticsearch-operator
