
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-metrics-monitor
spec:
  endpoints:
    - authorization:
        type: bearer
        credentials:
          key: token
          name: elasticsearch-operator-metrics-token
      path: /metrics
      targetPort: 8443
      scheme: https
      interval: 30s
      scrapeTimeout: 10s
      tlsConfig:
        ca:
          secret:
            key: service-ca.crt
            name: elasticsearch-operator-metrics-token
        serverName: elasticsearch-operator-metrics.openshift-operators-redhat.svc
  selector:
    matchLabels:
      name: elasticsearch-operator
