apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
spec:
  channel: "4.6"
  name: elasticsearch-operator
  source: elasticsearch-catalog
  sourceNamespace: openshift-operators-redhat
